version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    depends_on:
      - rabbitmq

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: ./user-service
    ports:
      - "8083:3000"
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network

  shopping-service:
    build:
      context: ./shopping-service
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
